services:
  user-service:
    image: distributed-programming-user:local
    build:
      context: ./modules/user
      dockerfile: Dockerfile
    environment:
      USER_MYSQL_ADDRESS: mysql:3306
      USER_AMQP_URL: amqp://local:local@rabbitmq:5672/
    ports:
      - "${USER_GRPC_PORT:-8081}:8081"
      - "${USER_HTTP_PORT:-8082}:8082"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  user-message-handler:
    image: distributed-programming-user:local
    command: [message-handler]
    environment:
      USER_MYSQL_ADDRESS: mysql:3306
      USER_AMQP_URL: amqp://local:local@rabbitmq:5672/
    ports:
      - "${USER_MESSAGE_HANDLER_PORT:-8083}:8082"
    depends_on:
      user-service:
        condition: service_started
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
